[greeter]
background=/usr/share/backgrounds/jalos/default.png
theme-name=Adwaita-dark
icon-theme-name=Adwaita
font-name=Cantarell 11
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format=%A, %B %d  %H:%M
position=50%,center 50%,center
