#!/bin/sh
set -e

VERSION=$(cat VERSION)

lb config noauto \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer live \
    --debian-installer-gui true \
    --apt-recommends false \
    --binary-images iso-hybrid \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "jalos ${VERSION}" \
    --iso-publisher "jalos Project" \
    --iso-volume "jalos-${VERSION}" \
    --bootloaders "grub-efi,syslinux" \
    --image-name "jalos-${VERSION}" \
    "${@}"