#!/bin/sh
set -e

lb config noauto \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer live \
    --debian-installer-gui true \
    --apt-recommends true \
    --binary-images iso-hybrid \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "jalos" \
    --iso-publisher "jalos Project" \
    --iso-volume "jalos" \
    --bootloaders "grub-efi" \
    --image-name "jalos" \
    "${@}"